  -- DA TA DEFINITION LANGUAGE                                                      
                                                        
                                                        -- DROP DATABASE DB;
       
DROP DATABASE DB;       
CREATE DATABASE DB;
USE DB;

CREATE TABLE STUDENTS
(ROLL_NO INT, NAME VARCHAR(25), GENDER CHAR(1), PHONE_NUMBER CHAR(10), DOB DATE, COURSES VARCHAR(25));

SELECT *
FROM STUDENTS;

INSERT INTO STUDENTS VALUES(1, "STEVE", "M", "9876543210", "1995-01-01", "DA");

INSERT INTO STUDENTS (ROLL_NO, NAME, PHONE_NUMBER, DOB, COURSES) 
VALUES(001, "SUDHEER", "9876543210", "1991-04-26","DA"); 

DESC STUDENTS;

CREATE TABLE STUDENTS(ROLL_NO INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(25), 
GENDER CHAR(1)CHECK( GENDER IN ("M","F","O")) DEFAULT "M", PHONE_NUMBER CHAR(10), DOB DATE, COURSES VARCHAR(25));

DESC STUDENTS;
DROP TABLE STUDENTS;

CREATE TABLE STUDENTS(ROLL_ID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(25), 
GENDER CHAR(1) CHECK (GENDER IN ("M","F","O")) DEFAULT "M", PHONE_NUMBER CHAR(10) UNIQUE, 
DOB DATE, COURSES VARCHAR(25) CHECK (COURSES IN ("DA", "DS", "DE", "AI", "ML","DL")));

INSERT INTO STUDENTS VALUES (3, "AHME", "F", "9696968574", "1999-02-02", "DS");

INSERT INTO STUDENTS VALUES (2, "RHME", "F", "9596968574", "1999-02-02", "DA");

INSERT INTO STUDENTS VALUES (1, "AHMED", "M", "9696968571", "1999-02-01", "ML");

SELECT * FROM STUDENTS;

INSERT INTO STUDENTS(NAME, PHONE_NUMBER, GENDER, DOB, COURSES) VALUES ("SAM", "8596741200", "F", "1898-08-13","ML");

CREATE TABLE MARKS (ID INT AUTO_INCREMENT, FOREIGN KEY (ID) REFERENCES STUDENTS (ROLL_ID) , 
NAME VARCHAR(25), 
GENDER CHAR(1) CHECK (GENDER IN ("M","F","O")) DEFAULT "M", 
PHONE_NUMBER CHAR(10) UNIQUE, 
DOB DATE, 
COURSES VARCHAR(25) CHECK (COURSES IN ("DA", "DS", "DE", "AI", "ML","DL")));

CREATE TABLE MARKS(M_ID INT AUTO_INCREMENT, FOREIGN KEY (M_ID) REFERENCES STUDENTS (ROLL_ID),
SCORE FLOAT UNIQUE, 
GRADER CHAR(1) CHECK (GRADER IN ("X", "S", "A", "B")) DEFAULT "P");
INSERT INTO MARKS VALUES(001, 987.66, "X"); 
INSERT INTO MARKS VALUES(002, 499.5, "S");
INSERT INTO MARKS VALUES(004, 599.1,"A");
INSERT INTO MARKS VALUES (003, 333.10, "B"); 

SELECT * FROM TEACHERS;
SELECT *
FROM MARKS;

ALTER TABLE MARKS ADD NAME CHAR;
ALTER TABLE MARKS MODIFY NAME FLOAT;
ALTER TABLE MARKS RENAME COLUMN NAME TO AVG ;

ALTER TABLE MARKS RENAME TO SCORES;


SELECT * 
FROM SCORES;

ALTER TABLE SCORES RENAME COLUMN ID TO NO;
ALTER TABLE SCORES RENAME COLUMN NO TO ID;
ALTER TABLE SCORES RENAME TO MARKS;

ALTER TABLE MARKS DROP COLUMN AVG;

TRUNCATE TABLE MARKS;