
                                                          -- DAY - TWO -- 29-26

USE HR;
SELECT *
FROM EMPLOYEES;
-- LOGICAL OPERATOR 
-- AND, OR, NOT
SELECT *
FROM EMPLOYEES
WHERE first_name="Alexander" AND last_name="Hunold";


SELECT *
FROM EMPLOYEES
WHERE first_name="Alexander" OR last_name="Hunold";


SELECT *
FROM EMPLOYEES
WHERE NOT(first_name="Alexander" OR last_name="Hunold");

-- MEMBERSHIP OPERATOR --

SELECT *
FROM EMPLOYEES
WHERE SALARY IN (5000,10000,20000);

-- LIKE, BETWEEN, NULL --

SELECT *
FROM EMPLOYEES
WHERE first_name LIKE "S%A";

SELECT * 
FROM EMPLOYEES
WHERE SALARY BETWEEN 5000 AND 10000;

SELECT *
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NULL;


SELECT *
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL;

-- SINGLE ROW FUNCTION --

-- TEXT FUNCTIONS --

SELECT "HELLO";

SELECT LOWER("HELLO");

SELECT UPPER("hello");

SELECT LEFT("HELLO",2);


SELECT RIGHT("HELLO",2);


SELECT MID("HELLO",2,3);


SELECT substr("HELLO",2,3);


SELECT INSTR("HEL-LO","-");

SELECT CONCAT("HELLO"," ", "WORLD") AS CON;

SELECT first_name,last_name, CONCAT(first_name, " ", last_name)
from employees as full_name;


-- NUMERICAL FUMCTION --

SELECT ABS(-9);

SELECT ROUND(9.5);

SELECT ROUND(9.5565,2);

SELECT CEIL(9.4); -- ROUND UP

SELECT FLOOR(9.5); -- ROUND DOWN 

SELECT MOD(10,3);

-- TRIM -- 

SELECT ("     hELLO");


SELECT TRIM(LEADING "$" FROM "$$$hELLO$$$$");


SELECT TRIM(TRAILING "$" FROM "$$$hELLO$$$$");


SELECT TRIM(BOTH "$" FROM "$$$hELLO$$$$");

-- DATE FUNCTION -- 

SELECT SYSDATE();

SELECT current_date();

SELECT MONTH (current_date());

-- ORDER BY -- 

SELECT * 
FROM EMPLOYEES
WHERE SALARY >= 10000
ORDER BY SALARY DESC;

-- AGGREGATION FUNCTION -- 

-- SUM,MIN,MAX,AVG,COUNT --

SELECT MAX(SALARY)
FROM EMPLOYEES;

SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID=90;

-- GROUP BY -- HAVING -- 

SELECT department_id,sum(salary) as total_salary
FROM employees
GROUP BY department_id
HAVING sum(salary)>20000
ORDER BY total_salary ;


