SHOW DATABASES;
USE HR;
SELECT *
FROM EMPLOYEES;

                                                                  -- DAY TWO TASKS-1 --

                                                    -- SQL Practice Tasks (Up to HAVING Clause)
                                                              -- Basic SELECT and WHERE
-- 1. List all employees with their first name, last name, and salary.
SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES;

-- 2. Find employees whose salary is more than 10,000.
SELECT * 
FROM EMPLOYEES
WHERE SALARY > 10000;

-- 3. List employees who were hired before 1st January 1995.
 SELECT * 
FROM EMPLOYEES
WHERE HIRE_DATE < '1995-01-01';


-- 4. Show all employees who do not have a commission.
SELECT * 
FROM EMPLOYEES
WHERE COMMISSION_PCT <> "NULL";

-- 5. Display the employees with job ID "IT_PROG".
SELECT * 
FROM EMPLOYEES
WHERE JOB_ID = "IT_PROG";

-- 6. Find employees working under manager_id 101.

SELECT * 
FROM EMPLOYEES
WHERE MANAGER_ID=101;

                                                                     -- GROUP BY Tasks

-- 7. Find the total salary paid in each department.

SELECT DEPARTMENT_ID, SUM(SALARY) AS TOT_SAL
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY TOT_SAL DESC;

-- 8. Count the number of employees in each job role.
SELECT JOB_ID, COUNT(EMPLOYEE_ID) AS S_EMP
FROM EMPLOYEES
GROUP BY JOB_ID
ORDER BY S_EMP DESC;

SELECT * FROM EMPLOYEES;

SELECT JOB_ID, COUNT(JOB_ID) AS TOT_COUNT 
FROM EMPLOYEES
GROUP BY JOB_ID
ORDER BY TOT_COUNT DESC;

-- 9. Get the average salary per department.
SELECT DEPARTMENT_ID, AVG(SALARY) AS A_SAL
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY A_SAL DESC;

SELECT * FROM EMPLOYEES;

SELECT DEPARTMENT_ID, AVG(SALARY) AS AVG_SAL
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY AVG_SAL DESC;

-- 10. Find the maximum salary for each job ID.

SELECT JOB_ID, MAX(SALARY) AS M_SAL
FROM EMPLOYEES
GROUP BY JOB_ID
ORDER BY M_SAL DESC;

SELECT * FROM EMPLOYEES;

SELECT JOB_ID, MAX(SALARY) AS MAX_SAL
FROM EMPLOYEES
GROUP BY JOB_ID
ORDER BY MAX_SAL DESC;

 -- ORDER BY Tasks
-- 11. List all employees ordered by their salary in descending order.


SELECT * FROM EMPLOYEES;

SELECT *
FROM EMPLOYEES
ORDER BY SALARY DESC;

-- 12. Display employees ordered by hire_date (earliest first).
SELECT *
FROM EMPLOYEES
ORDER BY HIRE_DATE;


 -- HAVING BY Tasks
 
-- 13. List departments with more than 2 employees.
-- SELECT DEPARTMENT_ID
-- FROM EMPLOYEES
-- GROUP BY DEPARTMENT_ID
-- HAVING (DEPARTMENT_ID>2);
SELECT DEPARTMENT_ID
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING COUNT(*) > 2;

SELECT DEPARTMENT_ID, COUNT(DEPARTMENT_ID) AS C_DEP
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING C_DEP > 2
ORDER BY C_DEP DESC;

-- 14. Show job IDs where the average salary is greater than 9,000.

SELECT JOB_ID, AVG(SALARY) AS AVG_SA
FROM EMPLOYEES
GROUP BY JOB_ID
HAVING AVG_SA > 9000
ORDER BY AVG_SA DESC;


SELECT *
FROM EMPLOYEES;

SELECT JOB_ID, AVG(SALARY) AS AVG_SAL
FROM EMPLOYEES
GROUP BY JOB_ID
HAVING (AVG_SAL>9000);

-- 15. Find departments where the total salary exceeds 25,000.
SELECT DEPARTMENT_ID, SUM(SALARY) AS TOT_SAL
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING TOT_SAL > 25000;

-- 16. List job roles with more than one employee who has NULL commission.
--  SELECT JOB_ID
--  FROM EMPLOYEES
--  HAVING JOB_ID > 2 
--  WHERE COMMISSION_PCT IS NULL;

SELECT JOB_ID, COUNT(JOB_ID) AS TOT_JR
FROM EMPLOYEES
WHERE commission_pct IS NULL 
GROUP BY JOB_ID
HAVING TOT_JR > 1;

SELECT *
FROM EMPLOYEES;

SELECT JOB_ID
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NULL
GROUP BY JOB_ID
HAVING COUNT(*) > 1;

-- 17. Find departments where the minimum salary is less than 5,000.

SELECT DEPARTMENT_ID, MIN(SALARY) AS MIN_SA
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING MIN_SA < 5000;

SELECT *
FROM EMPLOYEES;

SELECT DEPARTMENT_ID, MIN(SALARY) AS MIN_SAL
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING (MIN_SAL < 5000);

-- 18. Display job roles with total salary between 20,000 and 50,000.
SELECT * FROM EMPLOYEES;
SELECT JOB_ID, SUM(SALARY) AS TTS
FROM EMPLOYEES
GROUP BY JOB_ID
HAVING TTS BETWEEN 20000 AND 50000;

-- SELECT JOB_IB, SALARY
-- FROM employees
-- GROUP BY JOB_ID
-- WHERE SALARY BETWEEN 20000 AND 50000;

SELECT JOB_ID, SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEES
GROUP BY JOB_ID
HAVING SUM(SALARY) BETWEEN 20000 AND 50000;



                --  Challenge Tasks
-- 19. List departments where the number of employees is between 2 and 5.

SELECT DEPARTMENT_ID, COUNT(DEPARTMENT_ID) AS CDI
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING CDI BETWEEN 2 AND 5;

SELECT * FROM EMPLOYEES;

SELECT DEPARTMENT_ID
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING COUNT(DEPARTMENT_id) BETWEEN 2 AND 5;

-- 20. Show job IDs having total salary > 20,000 and at least 2 employees.

SELECT JOB_ID, COUNT(JOB_ID) AS CJI, SUM(SALARY) AS SUMSA
FROM EMPLOYEES
GROUP BY JOB_ID
HAVING CJI > 1  AND SUMSA > 20000;

SELECT *
FROM EMPLOYEES;

SELECT JOB_ID, SUM(SALARY) AS TOT_SAL
FROM EMPLOYEES
GROUP BY JOB_ID
HAVING COUNT(JOB_ID) > 1 AND TOT_SAL > 20000; 
